Unfortunately, you <strong>cannot</strong> change accommodation 
type using this form. 

<p> What you can do thought, is to <strong>add new accommodation</strong> 
    and deactive this one. 
    If you would like to do this, click
     <a href="<?php echo $this->baseUrl('accommodation/migrate/id/' . $this->urlParams('id'));?>">here</a>.    
</p>
<p> 
    We can prefill new accommodation form with some data, to make this process
    easy.
</p>

