<p>
    Niestety, <strong>nie można</strong> zmienić typu akomodacji. 
</p>

<p>Zamiast tego możesz <strong>dodać nowe ogłoszenie</strong> 
    i deaktywować to. 
    Aby Ci w tym pomóc, możemy częściowo wypełnic za Ciebie formularz 
    do dodania
    nowego ogłoszenia. Zdjęcia będzie trzeba na nowo uplądować.
    Jesli chcesz tak zrobić, nacisnij 
    <a href="<?php echo $this->baseUrl('accommodation/migrate/id/' . $this->urlParams('id'));?>">
        tutaj
    </a>.
    
</p>
<p> 
    Przepraszamy za niewygode. 
</p>

