<p>Twoja oferta własnie zostala dodana do naszej bazy danych.
Jednak jeszcze <strong>nie została aktywowana</strong>.
</p>
<?php if ($this->isLogged()): ?>
    <p> Jeśli chcesz <br /><br />
        <a class="acc-add" href="<?php echo $this->baseUrl('/accommodation/enable/id/' . $this->options['acc_id']); ?>" alt="Activate">
            aktywuj ją teraz
        </a>
        <br /><br /> 
        Jeśli chcesz <strong>coś zmienić</strong> naciśnij
        <a class="acc-add" href="<?php echo $this->baseUrl('/accommodation/edit/id/' . $this->options['acc_id']); ?>" alt="Edit">
            edytuj teraz
        </a>
        
        
    </p>
<?php else: ?>
    <p>
        Aby ją aktywować albo zmienić proszę się
         <a href="<?php echo $this->baseUrl('login'); ?>">zalogować</a>. 
        <br/>
    </p> 
<?php endif; ?>
