<p>Twoja oferta wlasnie zostala dodana do naszej bazy.
Jednak jeszcze <strong>nie zostala aktywowana</strong>.
</p>
<?php if ($this->isLogged()): ?>
    <p> Jesli chcesz <br /><br />
        <a class="acc-add" href="<?php echo $this->baseUrl('/accommodation/enable/id/' . $this->options['acc_id']); ?>" alt="Activate">
            aktywuj ja teraz
        </a>
        <br /><br /> 
        Jesli chcesz <strong>cos zmienic</strong> nacisnij
        <a href="<?php echo $this->baseUrl('/accommodation/edit/id/' . $this->options['acc_id']); ?>">tutaj</a>.
    </p>
<?php else: ?>
    <p>
        Aby ja aktywowac albo zmienic prosze sie
         <a href="<?php echo $this->baseUrl('login'); ?>">zalogowac</a>. 
        <br/>
    </p> 
<?php endif; ?>
