<p>
    Niestety, <strong>nie mozna</strong> zmienic typu akomodacji. 
</p>

<p>Zamiast tego mozesz <strong>dodac nowe add ogloszenie</strong> 
    i deaktywowac to. 
    Aby Ci w tym pomoc, mozemy częściowo wypełnic za Ciebie formularz do dodania
    nowego ogloszenia. Jednak zdjęcia będzie trzeba na nowo uplądować.
    Jesli chcesz tak zrobic, nacisnij 
    <a href="<?php echo $this->baseUrl('accommodation/migrate/id/' . $this->urlParams('id'));?>">tutaj</a>.
    
</p>
<p> 
    Przepraszamy za niewygode. 
</p>

