<p>Zachęcamy do <a href="<?php echo $this->baseUrl('/login');?>">zalogowania</a> 
    się
przed wypenieniem tego formularza. Dzięki usłudze <strong>OpenID</strong> 
jest to
niezwykle proste!
</p>
<p>
    Jeśli nie jesteś zalogowany, nowe konto w naszym systemie zostanie stworzone 
    podczas dodania pierwszego ogłoszenia.
</p>
<p>
    Używając swojego konta, bedziesz mogł edytować swoje ogłoszenia, 
    aktywować / deaktywować całe ogłoszenie,      
    albo dodać nowe. 
</p>