<p>Uzywajac tego formularza mozesz zalozyc u nas koto jestli nie masz, lub nie chcesz
kozystac z uslugi OpenID.
</p>
<p>W przeciwienstwie do innych, nie potrzebujemy twojego imienia i nazwiska,
    telefonu, adressu. Jedyne co jest potrzebne to <strong>address email</strong>
    na ktory uzytkownicy beda mogli kontaktowac sie z taba w sprawie 
    twoich ogloszen.   
    </p>
<p>
    Standardowo twoj email i telefon (jesli podany) nie sa <strong>wyswietlane</strong>.
    Jesli jednak chcesz aby byly one widoczne dla wszystkich, mozesz je oznakowac
    jako takie.     
</p>  