<p>
    Używajac tego formularza możesz założyć u nas konto jeśtli nie masz,
    lub nie chcesz
    korzystać z usługi OpenID.
</p>
<p>
    W przeciwienstwie do innych, nie potrzebujemy twojego imienia i nazwiska,
    telefonu czy adresu. Jedyne co jest potrzebne to
    <strong>address email</strong>
    na który użytkownicy będą mogli kontaktować się z tobą w sprawie 
    twoich ogłoszeń.   
</p>
<p>
    Standardowo twoj email i telefon (jeśli podany) nie są 
    <strong>wyświetlane</strong>.
    Jeśli jednak chcesz aby były one widoczne dla wszystkich, 
    mozesz je oznakować
    jako takie.     
</p>  