<?php
$pages = array(
    'about' => 'aboutpage',
    'legal' => 'legalpage',
    'privacy policy' => 'privacypage',
    'contact' => 'contactpage'
);
?>



<ul class="top-cities">
    
    <?php 
    
    // links to be skiped, i.e. not rendered
    $skip = array();
    
    if (isset($this->options['options']['skip'])) {
        $skip = $this->options['options']['skip'];
    }
    
    foreach ($pages as $label => $route):               
        
//        if (in_array($label, $skip)) {            
//            continue;
//        }
        
        $url = $this->url(array(), $route);
        $label = $this->translate($label);                
        
        echo "<li><a href=\"$url\">".ucfirst($label)."</a></li>";
        
    endforeach;

    
    ?>

</ul>