<p>
    It seems that your OpenID provider did not provided us with an email. 
    An email address is needed to be able to contact with you.
</p>
<p>   
<strong>If you want</strong> you can provide some additional information. If you
    don't want it is fine with us. Just make sure that your email is correct since
    user quires regarding your advertisment will be sent to this email address.
</p>
<p>
    By default your email or phone are kept <strong>private</strong>. However, if you want you 
    can make them public so that 
    they are visible to the people watching your accommodation.
</p>   