<?php
// get the list of top cities in the database,
// based on the number of offers.

$cache = Zend_Registry::get('frontsidebarCache');
$cities = $cache->load('topCities');

if (!$cities) {

    $cities = '<ul class="top-cities">';

    $results = My_Model_Table_Accommodation::getTopCities();

    foreach ($results as $city) {
        $cities .= '<li><a href="' . $this->baseUrl('/accommodation/list/city/' . $city['city_id']) . '">' . $city['name'] . ' <span>(' . $city['count'] . ')</span></a></li>';
    }

    $cities .= '</ul>';
    $cache->save($cities, 'topCities');
}

echo $cities;
?>


