<p><strong>Używamy OpenID</strong>. Możesz się zalogować używając swojego
    konta Google, Yahoo albo Facebook. 
</p>
<p><strong>Jesteśmy darmowi</strong>.  Dodawanie ogłoszeń,
czytanie, kontaktowanie się jest darmowe. 
</p>


<p><strong>Brak limitacji</strong>. Można posiadać ile się chce ofert. 
</p>

<p style="text-align: right;">
    <a  href="<?php echo $this->baseUrl('/about');?>">Więcej</a>
</p>
