<strong>It is 100% free</strong>.  It is free to 
post advertisments, browse them, contact and send messages. 

<p><strong>It is OpenID enabled</strong>. You don\'t need to fill out any
    registration forms if you don\'t want. Just use your existing
    Google, Yahoo or Facebook account to login. </p>

<p><strong>It's not complicated</strong>. Our interface is clean, 
    simple and easy to use. Often, less is better.
</p>

<p style="text-align: right;">
    <a  href="<?php echo $this->baseUrl('/about');?>">Learn more</a>
</p>