<p><strong>Jest 100% darmowe</strong>.  Dodawanie ogleszen,
przegladanie, kontaktowanie sie czy wysylanie wiadomosci jest darmowe. 
</p>
<p><strong>Uzywamy OpenID</strong>. Mozesz uzyc swojego dotychasowego konta z Google,
    Yahoo czy Facebooka aby sie zalogowac. 
</p>

<p><strong>Jest proste</strong>. Nasz glowny priorytet to jest wygoda i prostota
    w uzyciu.
</p>

<p style="text-align: right;">
    <a  href="<?php echo $this->baseUrl('/about');?>">Wiecej</a>
</p>
