<div class="grid_6">
    <h1>O nas</h1>    
</div>
   

<div class=" grid_6 static">    
    <p>
        <?php echo SITE_NAME;?> jest strona dla bla bla. 
    </p>
</div>    

<div class=" grid_6 static">
    <h1>No i co z tego? Co jest takiego innego od dziesiatki innych takich stron?</h1>   
        
    
    <h2>It is OpenID enabled</h2>
    <p> You don\'t need to fill out any
       registration forms if you don\'t want. Just use your existing
        Google, Yahoo or Facebook account to login. 
    </p>
    
    
    <h2>It is 100% free</h2>    
    <p>
        It is free to 
        post advertisments, browse them, contact and send messages. 
    </p>
    
    
    <h2>You control your contact details</h2>    
    <p>
        It is free to 
        post advertisments, browse them, contact and send messages. 
    </p>
    
    
    <h2>It's not complicated</h2>    
    <p> Our interface is clean, 
    simple and easy to use. Often, less is better.
    </p>
    
     <h2>Your opinion matters</h2>    
    <p> Our interface is clean, 
    simple and easy to use. Often, less is better.
    </p>
    
    <h2>We constantly are improving it</h2>    
    <p>
        It is free to 
        post advertisments, browse them, contact and send messages. 
    </p>
</div>
        
    
    
    