<div class="grid_6">
    <h1>About</h1>    
</div>
    
<div class=" section grid_6 omega">    
    <p>
        ShareHouse is a website for looking for tentants, wanting to rent an 
        accommodation. 
    </p>
</div>    

<div class=" section grid_6 omega">
    <h1>So what? What is so different from a dozen of other websites like this</h1>   
    <strong>It is 100% free</strong>.  It is free to 
        post advertisments, browse them, contact and send messages. 
       
       <p><strong>It is OpenID enabled</strong>. You don\'t need to fill out any
       registration forms if you don\'t want. Just use your existing
        Google, Yahoo or Facebook account to login. </p>
        
    <p><strong>It\'s not complicated</strong>. Our interface is clean, 
    simple and easy to use. Often, less is better.
    </p>
</div>
        
    
    
    