<?php
    echo $this->partial('_partials/sidebar-for-pages.phtml',array('skip' => array('contact')))
?>   

<div class="grid_6 alpha">
    <h1>Kontakt</h1>    
</div>
    
<div class="grid_6 static alpha">    
    <h2>Uwagi ogólne</h2>
    <p>
      Ogólne uwagi związane z działaniem portalu prosimy kierować na adres:
      
    </p>
    
    <h2>Inne</h2>
    <p>
     Ogólne uwagi związane z działaniem portalu prosimy kierować na adres:
      
    </p>
</div>    
 
    