<?php
    echo $this->partial('_partials/sidebar-for-pages.phtml',array('skip' => array('contact')))
?>   

<div class="grid_6 alpha">
    <h1>Kontakt</h1>    
</div>
    
<div class="grid_6 static alpha">    
    <h2>Uwagi ogólne</h2>
    <p>
      Ogólne uwagi czy sugestje związane z działaniem portalu prosimy zgłaszać
      używając  usługi 
      <a href="javascript:UserVoice.showPopupWidget();" 
         title="Open feedback & support dialog (powered by UserVoice)">
          UserVoice</a>.
      
      
    </p>
    
    <h2>Inne</h2>
    <p>
     W sprawie innych spraw prosimy pisać na adres:
     <a href="mailto:kontakt@strefastancji.pl">kontakt@strefastancji.pl</a>.
      
    </p>
</div>    
 
    
