<?php
echo $this->partial('_partials/sidebar-for-pages.phtml', array('skip' => array('legal')))
?>   

<div class="grid_6 alpha">
    <h1>Regulamin</h1>    
</div>

<div class=" grid_6 static alpha">    
    <p>&nbsp;</p>
    <p>
        Przed korzystaniem z naszego portalu, 
        prosimy o zapoznanie się z jego regulaminem. 
    </p>
</div>    

<div class=" grid_6 static alpha">

    <h2>Punkt pierwszy</h2>
    <p>
        Osoba dodająca ofertę jest zobowiązana do korzystania z 
        portalu zgodnie z obowiązującym prawem, 
        normami społecznymi, obyczajowymi oraz niniejszym regulaminem.
    </p>    


    <h2>Punkt drugi</h2>
    <p>
        Portal <?php echo SITE_NAME; ?> nie bierze 
        odpowiedzialności za treść zamieszczanych ofert, 
        reklam oraz opinii użytkowników. Dodatkowo
        za zgłoszenie fałszywych informacji  
        odpowiedzialność spoczywa na osobie podającej takie 
        informacje.        
    </p>




    <h2>Punkt trzeci</h2>
    <p> 
        Portal <?php echo SITE_NAME; ?>  zastrzega sobie prawo do 
        edycji błędnie wprowadzonych ofert 
        lub ich usunięcia jeśli są one niezgodne z 
        tematyką portalu albo niniejszym regulaminem.   
    </p>


    <h2>Punkt czwarty</h2>
    <p> 
        Użytkownik oświadcza, iż posiada odpowiednie zgody i uprawnienia do
        zamieszczanych materiałów w portalu <?php echo SITE_NAME; ?>.
    </p>

    <h2>Punkt piąty</h2>
    <p> 
        Zamieszczane w portalu <?php echo SITE_NAME; ?> zdjęcia 
        powinny przedstawiać wyłącznie
        pokój/mieszkanie, którego dotyczą.  Zabronione jest dodawanie 
        zdjęć niezwiązanych
        z daną ofertą albo takich, które przedstawiają osoby.
    </p>


    <h2>Punkt szósty</h2>
    <p> 
        Osoba zgłaszająca ofertę wyraża zgodę na 
        przetwarzanie danych swoich i oferty na
        potrzeby funkcjonowania portalu.  
    </p>



    <h2>Punkt siódmy</h2>
    <p> 
        Zgłoszone oferty są automatycznie deaktywowane po 
        dwóch tygodniach od ich utworzenia/aktywowania. 
        Użytkownik może aktywować z powrotem
        nieaktywną ofertę po zalogowaniu się do portalu.           
    </p>




    <h2>Punkt ósmy</h2>
    <p> 
        Portal <?php echo SITE_NAME; ?> nie ponosi 
        odpowiedzialności za osoby poszukujące zakwaterowania, jak i osoby
        zgłaszające oferty, oraz szkody wynikłe z ich działań.                  
    </p>



    <h2>Punkt dziewiąty</h2>
    <p>
        Portal <?php echo SITE_NAME; ?> nie ponosi odpowiedzialności za
        skutki wynikłe 
        z ujawnienia wszelkich wprowadzonych danych osobom trzecim, 
        niezależnie od przyczyny ujawnienia.
        Portal zobowiązuje się, do dołożenia  
        starań w celu ochrony tych danych.                        
    </p>



    <h2>Punkt dziesiąty</h2>
    <p> 
        Korzystanie z serwisu jest jednoznaczne z akceptacją regulaminu.   
    </p>
    

    <h2>Punkt jedenasty</h2>
    <p> 
        Portal <?php echo SITE_NAME; ?> zastrzega 
        sobie prawo do wprowadzania zmian w niniejszym reglaminem. 
    </p>




</div>




