<?php
    echo $this->partial('_partials/sidebar-for-pages.phtml',array('skip' => array('legal')))
?>   

<div class="grid_6 alpha">
    <h1>Regulamin</h1>    
</div>

<div class=" grid_6 static alpha">    
    <p>&nbsp;</p>
    <p>
       Przed korzystaniem z naszego portalu, 
        prosimy o zapoznanie się z jego regulaminem. 
    </p>
</div>    

<div class=" grid_6 static alpha">
   
    <h2>Punkt pierwszy</h2>
    <p>
        Osoba dodająca ofertę jest zobowiązana do korzystania z 
        portalu zgodnie z obowiązującym prawem, 
        normami społecznymi i obyczajowymi oraz postanowieniami tego regulaminu.
    </p>    

    
    <h2>Punkt drugi</h2>
    <p>    
        <?php echo SITE_NAME; ?> nie ponosi odpowiedzialności za treść ogłoszeń.
    </p>

    <h2>Punkt trzeci</h2>
    <p> 
    <?php echo SITE_NAME; ?>  zastrzega sobie prawo do 
      modyfikacji błędnie wprowadzonych danych 
      lub usunięcia oferty która jest niezgodna z tematyką portalu czy regulaminem.   
    </p>

    <h2>Punkt czwarty</h2>
    <p> 
    Użytkownik oświadcza, iż posiada odpowiednie zgody i uprawnienia do
    materiałów umieszczonych na portalu <?php echo SITE_NAME; ?> .
    </p>

    <h2>Punkt piąty</h2>
    <p> 
    Zamieszczane w poratlu zdjęcia powinny przedstawiać wyłącznie
    pokój/mieszkanie, której dotyczą.  Zabronione jest dodawanie zdjęć nie związanych
    z daną stancją albo takich które przedstawiają osoby.
    </p>
    
    
    <h2>Punkt szósty</h2>
    <p> 
       Osoba zgłaszająca ofertę wyraża zgodę na 
       przetwarzanie danych oferty na
       potrzeby funkcjonowania portalu.  
    </p>
    
    
       
    <h2>Punkt siódmy</h2>
    <p> 
      Za zgłoszenie nieprawdziwych informacji      
      odpowiedzialność spoczywa na osobie zgłaszającej.    
    </p>
    
    
         
    <h2>Punkt ósmy</h2>
    <p> 
        <?php echo SITE_NAME; ?> nie ponosi 
        odpowiedzialności za osoby poszukujące stancji, 
        mieszkań i innych lokali oraz szkody wynikłe z działań tych osób. 
    </p>
    
    
    
    <h2>Punkt dziewiąty</h2>
    <p>
        Portal <?php echo SITE_NAME; ?> nie ponosi odpowiedzialności za
        skutki wynikłe 
        z ujawnienia wszelkich wprowadzonych danych osobom trzecim, 
        niezależnie od przyczyny ujawnienia.
        Jedank zobowiązuje się, do dołoży wszelkich 
        starań w celu ochrony tych danych.                        
        
    </p>

    
           
    <h2>Punkt dzieśiąty</h2>
    <p> 
     Korzystanie z serwisu jest jednoznaczne z akceptacją regulaminu.   
    </p>
    
    <h2>Punkt jedensaty</h2>
    <p>
         Portal <?php echo SITE_NAME; ?> nie bierze 
        odpowiedzialności za zamieszczone oferty, 
        reklamy oraz opinie użytkownikosz. W szczególności 
        Serwis instancje.pl oraz nie ponosi odpowiedzialności 
        za osoby poszukujące stancji, mieszkań i innych lokali
        oraz szkody wynikłe z działań tych osób.
    </p>
                    
</div>




