<div class="grid_6">
    <h1>Regulamin</h1>    
</div>



<div class=" grid_6 static">
    <h1>Przed korzystaniem z naszego portalu, prosimy o zapoznanie się z jego regulaminem</h1>
    
    <h2>Punkt pierwszy</h2>
    <p>
        Osoba dodająca ofertę jest zobowiązana do korzystania z 
        portalu zgodnie z obowiązującym prawem, 
        normami społecznymi i obyczajowymi oraz postanowieniami tego regulaminu.
    </p>    

    <h2>Punkt drógi</h2>
    <p>
        Portal <?php echo SITE_NAME; ?> nie ponosi odpowiedzialności za skutki wynikłe 
        z ujawnienia wszelkich wprowadzonych danych osobom trzecim, 
        niezależnie od przyczyny ujawnienia (np.: awari albo włamana do portalu).
        Jedank zobowiązuje się, do dołoży wszelkich starań w celu ochrony tych danych.
    </p>

    
    <h2>Punkt trzeci</h2>
    <p>    
        <?php echo SITE_NAME; ?> nie ponosi odpowiedzialności za treść ogłoszeń.
    </p>

    <h2>Punkt czwarty</h2>
    <p> 
    Serwis  zastrzega sobie prawo do odmowy publikacji oferty, 
      modyfikacji błędnie wprowadzonych danych 
      lub usunięcia oferty bez podania przyczyny.   
    </p>

    <h2>Punkt piąty</h2>
    <p> 
    Użytkownik oświadcza, iż posiada odpowiednie zgody i uprawnienia do
    materiałów umieszczonych w Serwisie.
    </p>

    <h2>Punkt szósty</h2>
    <p> 
    Zamieszczane w Serwisie zdjęcia powinny przedstawiać wyłącznie
    stancję, której dotyczą, zabronione jest dodawanie innych zdjęć,
    a także takich, na których widnieją osoby.
    </p>
    
    
    <h2>Punkt szósty</h2>
    <p> 
       Zgłaszający wyraża zgodę na przetwarzanie danych oferty na
       potrzeby funkcjonowania Serwisu.  
    </p>
    
    
       
    <h2>Punkt szósty</h2>
    <p> 
      Za zgłoszenie nieprawdziwych informacji 
      odpowiedzialność spoczywa na osobie zgłaszającej.    
    </p>
    
    
       
    <h2>Punkt szósty</h2>
    <p> 
     
    </p>
    
    
    
       
    <h2>Punkt szósty</h2>
    <p> 
        Instancje.pl oraz Fundacja MANUS nie ponosi 
        odpowiedzialności za osoby poszukujące stancji, 
        mieszkań i innych lokali oraz szkody wynikłe z działań tych osób. 
    </p>
    
    
           
    <h2>Punkt szósty</h2>
    <p> 
     Korzystanie z serwisu jest jednoznaczne z akceptacją regulaminu   
    </p>
    
    
           
    <h2></h2>
    <p> 
        
    </p>
    
    
    
</div>




