<?php
    echo $this->partial('_partials/sidebar-for-pages.phtml',array('skip' => array('privacy policy')))
?>   

<div class="grid_6 alpha">
    <h1>Polityka prywatności</h1>    
</div>
   

<div class=" grid_6 static alpha">
      
    
    <h2>It is OpenID enabled</h2>
    <p> You don\'t need to fill out any
       registration forms if you don\'t want. Just use your existing
        Google, Yahoo or Facebook account to login. 
    </p>
       
</div>
        
    
    
    
