<!-- ----------- RECENTLY VIEWED ADVERS ---------- -->

<?php
$sideBarHtml = $this->partial('_partials/add-this.phtml', array('title' => false));
$this->sideBarElement('Spread the word', $sideBarHtml);
?>   



<?php
// permanent placeholder for recently viewed adds

$cache = Zend_Registry::get('frontsidebarCache');
$accs = $cache->load('recentlyViewd');
if (!$accs) {
    $accs = '<ul class="top-cities">';

    $results = My_Model_Table_Accommodation::getRecentlyViewed();

    foreach ($results as $acc) {
        $title = $this->truncate(ucfirst(strtolower($acc['title'])), 0, 25);
        $accs .= '<li><a href="' . $this->baseUrl('/accommodation/show/id/' . $acc['acc_id']) . '">' . $title . ' <span>(' . $acc['city'] . ')</span></a></li>';
    }

    $accs .= '<ul class="top-cities">';
    $cache->save($accs, 'recentlyViewd');
    
}

$this->sideBarElement('Recently viewed', $accs, array('place' => 'prepend'));
?>

<?php
$sideBarHtml = 'partialfile:top-cities';
$this->sideBarElement('Top cities', $sideBarHtml, array('place' => 'prepend'));
?>


<?php
// permanent placeholder for map view

$mapDiv = '<div id="map" style="height: 260px"></div>
          <p class="side-bar-link" style="text-align:right;">
          <a href="'.$this->baseUrl('accommodation/full-map-view').'">'.$this->translate('Full map view').'</a>
          </p>';


$this->sideBarElement('Map view', $mapDiv, array('place' => 'prepend'));
?>
<script type="text/javascript" src="<?php echo $this->baseUrl('/js/mapmainpage.js'); ?>"></script>

<script type="text/javascript">
    $(function() {
        // center map in poland 
        showMarker(52.385459, 19.131691,5); 
    });
</script>

<?php
$sideBarContent = 'partialfile:why-sharehouse';
$this->sideBarElement('Why ShareHouse?', $sideBarContent, array('class' => 'side-bar-info'));
?>
<?php
$sideBarContent = '<br/>
       <a class="acc-add" href="' .  $this->url(array(), 'accadd') . '" alt="Add accommodation">'.$this->translate('Add accommodation').'</a>
           <br/><br/><br/>';
$this->sideBarElement('', $sideBarContent);
?>
<?php
    //$this->layout()->mainForm = $this->mainForm;
?>
<div id="welcome">    
    <?php         
      //  $t1 = microtime(true);
       // if (!$this->viewCache()->start('mainForm')) {
            echo $this->mainForm; 
        //    $this->viewCache()->end();
       // }
       // $t2 = microtime(true);
      //  echo $t2-$t1;
    ?>
</div>


<?php echo $this->recentAdverts($this->page); ?>

