<!-- ----------- RECENTLY VIEWED ADVERS ---------- -->

<?php
$sideBarHtml = $this->partial('_partials/add-this.phtml', array('title' => false));
$this->sideBarElement('Spread the word', $sideBarHtml);
?>   



<?php
// permanent placeholder for recently viewed adds

$cache = Zend_Registry::get('frontsidebarCache');
$accs = $cache->load('recentlyViewd');
if (!$accs) {
    $accs = '<ul class="top-cities">';

    $results = My_Model_Table_Accommodation::getRecentlyViewed();

    foreach ($results as $acc) {
        $title = $this->truncate(ucfirst(strtolower($acc['title'])), 0, 25);
        $accs .= '<li><a href="' . $this->baseUrl('/accommodation/show/id/' . $acc['acc_id']) . '">' . $title . ' <span>(' . $acc['city'] . ')</span></a></li>';
    }

    $accs .= '<ul class="top-cities">';
    $cache->save($accs, 'recentlyViewd');
    
}

$this->sideBarElement('Recently viewed', $accs, array('place' => 'prepend'));
?>
<?php
// permanent placeholder for top cities

$cache = Zend_Registry::get('frontsidebarCache');
$cities = $cache->load('topCities');

if (!$cities) {

    $cities = '<ul class="top-cities">';

    $results = My_Model_Table_Accommodation::getTopCities();

    foreach ($results as $city) {
        $cities .= '<li><a href="' . $this->baseUrl('/accommodation/list/city/' . $city['city_id']) . '">' . $city['name'] . ' <span>(' . $city['count'] . ')</span></a></li>';
    }

    $cities .= '<ul class="top-cities">';
    $cache->save($cities, 'topCities');
}

$this->sideBarElement('Top cities', $cities, array('place' => 'prepend'));
?>


<?php
// permanent placeholder for map view

$mapDiv = '<div id="map" style="height: 260px"></div>';


$this->sideBarElement('Map view', $mapDiv, array('place' => 'prepend'));
?>
<script type="text/javascript" src="<?php echo $this->baseUrl('/js/mapmainpage.js'); ?>"></script>

<script type="text/javascript">
    $(function() {
        // center map in poland 
        showMarker(52.385459, 19.131691,5); 
    });
</script>

<?php
$sideBarContent = '
        <strong>It is 100% free</strong>.  It is free to 
        post advertisments, browse them, contact and send messages. 
       
       <p><strong>It is OpenID enabled</strong>. You don\'t need to fill out any
       registration forms if you don\'t want. Just use your existing
        Google, Yahoo or Facebook account to login. </p>
        
    <p><strong>It\'s not complicated</strong>. Our interface is clean, 
    simple and easy to use. Often, less is better.
    </p>
    
        <p style="text-align: right;">
                <a  href="'.$this->baseUrl('/about').'">Learn more</a>
                </p>
       
       ';
$this->sideBarElement('Why ShareHouse?', $sideBarContent, array('class' => 'side-bar-info'));
?>
<?php
$sideBarContent = '<br/>
       <a class="acc-add" href="' . $this->baseUrl("/add") . '" alt="Add accommodation">Add accommodation</a>
           <br/><br/><br/>';
$this->sideBarElement('', $sideBarContent);
?>
<?php
    //$this->layout()->mainForm = $this->mainForm;
?>
<div id="welcome">    
    <?php         
      //  $t1 = microtime(true);
        if (!$this->viewCache()->start('mainForm')) {
            echo $this->mainForm; 
            $this->viewCache()->end();
        }
       // $t2 = microtime(true);
      //  echo $t2-$t1;
    ?>
</div>


<?php echo $this->recentAdverts($this->page); ?>

