  <!-- ----------- RECENTLY VIEWED ADVERS ---------- -->

<?php
// permanent placeholder for recently viewed adds

$accs = '<ul class="top-cities">';

$results = My_Model_Table_Accommodation::getRecentlyViewed();                                      

foreach ($results as $acc) {
    $title = $this->truncate(ucfirst(strtolower($acc['title'])),0, 25);
    $accs .= '<li><a href="'.$this->baseUrl('/accommodation/show/id/' . $acc['acc_id']).'">'.$title.' <span>('.$acc['city'].')</span></a></li>';
}

$accs .= '<ul class="top-cities">';

$this->sideBarElement('Just viewed',$accs, array('place' => 'prepend'));  
?>
 <?php
    // permanent placeholder for top cities

   $cities = '<ul class="top-cities">';

   $results = My_Model_Table_Accommodation::getTopCities();

   foreach ($results as $city) {
        $cities .= '<li><a href="'.$this->baseUrl('/accommodation/list/city/' . $city['city_id']).'">'.$city['name'].' <span>('.$city['count'].')</span></a></li>';
   }

   $cities .= '<ul class="top-cities">';

    $this->sideBarElement('Top cities',$cities, array('place' => 'prepend'));  
?>
<?php
   $sideBarContent = '
        <strong>It is 100% free</strong>.  It is free to 
        post advertisments, browse them, contact and send messages. 
       
       <p><strong>It is OpenID enabled</strong>. You don\'t need to fill out any
       registration forms if you don\'t want. Just use your existing
        Google, Yahoo or Facebook account to login. </p>
        
    <p><strong>It\'s not complicated</strong>. Our interface is clean, 
    simple and easy to use. Often, less is better.
    </p>
    
        <p style="text-align: right;">
                <a  href="http://openid.net/what/">Learn more</a>
                </p>
       
       ';
   $this->sideBarElement('Why houseshare?',$sideBarContent, array('class' => 'side-bar-info'));  
?>
<?php
   $sideBarContent = '<br/>
       <a class="acc-add" href="' . $this->baseUrl("/add").'" alt="Add accommodation">Add accommodation</a>
           <br/><br/><br/>';
   $this->sideBarElement('',$sideBarContent);  
?>
<div id="welcome">
    <?php echo $this->mainForm; ?>
</div>

               
 <?php echo $this->recentAdverts($this->page); ?>

