<?php
if (!$this->isLogged()):
    $sideBarContent = '
            We encourage to <a href="' . $this->baseUrl('/login') . '">login</a> before 
                filling this form or to register if you are first time here. 


            <p> Otherwise, the account will be created during the first submission. </p>
           <p> The account will allow you to modify your advertisment or disable it at a
           a later date.
                   </p>

           ';
    $this->sideBarElement('Better to login?', $sideBarContent, array('class' => 'side-bar-info', 'break' => true));

endif;
?>

<?php
echo $this->partial('_partials/acc-add-steps-desc.phtml', null, array('active' => 'step1'));
?>

<div class="grid_6">  
    <h1> Step 1: Basic information </h1>
</div>
<div class="grid_6">
    <?php

    $cache = Zend_Registry::get('outputCache');
    
    if (empty($_POST)) {
        // show form from the cache only if $_POST is empty.
        if (!$cache->start('addForm')) {
            echo $this->form;
            $cache->end();
        }
    } else {
        echo $this->form;
    }

    ?>
</div>
