<?php
if ($this->showSteps) {
    echo $this->partial('_partials/acc-add-steps-desc.phtml', null, array('active' => 'step3'));
}

?>

<?php
if (isset($this->acc) && count($this->acc->photosurls) > 0) {
    $imgsHtml = $this->partial('_partials/acc-photos.phtml',array('acc' => $this->acc));
    $this->sideBarElement('Current photos', $imgsHtml);
}

if (!$this->showSteps) {
    echo $this->sideBarElement('Photos','partialfile:acc-add-step3',  array('class' => 'side-bar-info'));
}
?> 

<div class="grid_6">  
    <h1><?php echo $this->translate($this->title); ?></h1>
</div>
<div  class="grid_6">
   
    
    <div id="photos-upload-form">
        <?php echo $this->form; ?>
    </div>
  
     <div  id="progress"  style="display:none; width:100%"> 
        <img class="loadingimg"  src="<?php echo $this->baseUrl('/images/loading2.gif');?>" />
        <p style="text-align:center;">
            <?php echo $this->translate('Please wait.<br />It may take a while, depending on your Internet speed and size of the photos uploaded.');?>
        </p>
    </div>

</div>


<script type="text/javascript">
    $(document).ready(function (e) {
        
        var text = "<?php echo $this->translate('Please wait.<br />It may take a while, depending on your Internet speed and size of the photos uploaded.');?>";
        
        $('input#Upload').live('click', function(e) {   
            
            var loadingImgUrl = myGlobals['baseUrl'] + '/images/loading2.gif';
                    
            
            $('#photos-form').submit();
            
            $('#progress').show();
            
            
            $('#photos-upload-form').hide();
           
            if ($.browser.msie) {
               $('#progress').html('<img class="loadingimg" src="' + loadingImgUrl +'" /><p style="text-align:center;">'+text+'</p>');
            }
            
            return true;
           
        });
    });    

</script>
