<?php
    $sideBarContent = 'partialfile:acc-edit';
    $this->sideBarElement('Cannot change accommodation type?', $sideBarContent, array('class' => 'side-bar-info','break'=>true));

?>
<h2>Edit accommodation data</h2>
<div>
    <?php echo $this->form;?>
</div>

<script type="text/javascript">
    jQuery(function($){        
        // add info of how many characters left 
        myCharsLeft('basic_info-title', 80);   
        myCharsLeft('basic_info-description', 500);        
        myCharsLeft('basic_info-price_info', 60);        
        myCharsLeft('features-description', 100); 
        myCharsLeft('roomates-description', 100); 
        myCharsLeft('preferences-description', 100); 
        myCharsLeft('appartment_details-description', 100); 
        myCharsLeft('about_you-description', 100); 
    });
</script>