<?php
if (!is_null($this->limitForm)) {
    // setup content for the side bar placeholder   
    $this->sideBarElement('Limit the list', $this->limitForm);
}
?>

<?php
$sideBarHtml = 'partialfile:top-cities';
$this->sideBarElement('Top cities', $sideBarHtml, array('place' => 'prepend'));
?>

<?php
$sideBarContent = 'partialfile:full-map-view';
$this->sideBarElement('Full map view', $sideBarContent, array('class' => 'side-bar-info'));
?>  




<div class="grid_6">  
    &nbsp;
</div>

<input type="hidden" id="cityLat" value="<?php echo $this->cityLat ;?>" />
<input type="hidden" id="cityLng" value="<?php echo $this->cityLng ;?>" />

<div id="map" class="grid_6 alpha " style="height: 700px">  </div>


<script type="text/javascript">
    
    $(function(){
         
        $('button#limit').click(function(){           
            $('#limit-form').submit();  
        });
    });
</script>

<script type="text/javascript">
    accData = <?php echo json_encode($this->accData); ?>;
</script>

<script type="text/javascript" src="<?php echo $this->baseUrl('/js/markerclusterer.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('/js/fullmapview.js'); ?>"></script>


<div class="grid_6">
    <?php //echo $this->form; ?>
</div>
