<?php
$sideBarContent = 'partialfile:full-map-view';
$this->sideBarElement('Full map view', $sideBarContent, array('class' => 'side-bar-info'));
?>  




<div class="grid_6">  
    <h1><?php echo $this->translate('All on the map'); ?></h1>
</div>

<div id="map" class="grid_6 " style="height: 800px">  </div>


<script type="text/javascript">
    accData = <?php echo json_encode($this->accData); ?>;
</script>

<script type="text/javascript" src="<?php echo $this->baseUrl('/js/markerclusterer.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('/js/fullmapview.js'); ?>"></script>


<div class="grid_6">
    <?php echo $this->form; ?>
</div>
