<?php
   // setup content for the side bar placeholder   
   $this->sideBarElement('Limit the list', $this->limitForm);  
?>

<div>
        <?php echo $this->partial('_partials/_recentAdverts.phtml', null, 
                array(
                    'accommodations' => $this->accs,
                    'title'   => $this->listTitle,
                    'editMenu' => false
                )
                );    
        ?>
   </div>
