<?php
$sideBarHtml = $this->partial('_partials/add-this.phtml', array('title' => false));
$this->sideBarElement('Spread the word', $sideBarHtml);
?>   

<?php
$sideBarHtml = 'partialfile:top-cities';
$this->sideBarElement('Top cities', $sideBarHtml, array('place' => 'prepend'));
?>

<?php
// permanent placeholder for map view
$mapDiv = '<div id="map" style="height: 240px"></div>';
$this->sideBarElement('Map view', $mapDiv, array('place' => 'prepend'));
?>


<?php
// setup content for the side bar placeholder   
$this->sideBarElement('Limit the list', $this->limitForm);
?>


<script type="text/javascript" src="<?php echo $this->baseUrl('/js/mapmainpage.js'); ?>"></script>

<script type="text/javascript">
    $(function() {        
        // center map in the city
        var city_lat = <?php echo $this->cityRow->getMarker()->lat; ?>;
        var city_lng = <?php echo $this->cityRow->getMarker()->lng; ?>;
        showMarker(city_lat, city_lng, 11, true); 
    });
</script>

  <h1>
     <?php echo $this->translate('Accommodation in');?>
     <?php echo $this->city;?>
  </h1>
<div>
    <?php
    if (count($this->accs) > 0):
        echo $this->partial('_partials/_recentAdverts.phtml', null, array(
            'accommodations' => $this->accs,
            'title' => '',
            'editMenu' => false
                )
        );
    ?>
    
    <?php else: ?>
    <br />
    <h3>
        <?php echo $this->translate('No accommodetion were found with the selected criteria' );?>
    </h3>
    
    <?php endif;?>
</div>

<script type="text/javascript">
    
    $(function(){
         
        $('button#limit').click(function(){           
            $('#limit-form').submit();  
        });
        
        var previouseTxt = "<?php echo $this->translate('Previous');?>";
        var nextTxt = "<?php echo $this->translate('Next');?>";
         
        $('.paginationControl a').click(function (event) {
         
            event.preventDefault();
           
            // get new page number
            var html = $.trim($(this).html());
            var newPage = parseInt(html);
           
            // get current page number
            var htmlCurrentPage = $.trim($('.current-page').html());
         
            var currentPage = parseInt(htmlCurrentPage);
           
            // correct in case previouse or next button clicked
            if (isNaN(newPage)) {
                if (html == previouseTxt) {                   
                    newPage = currentPage - 1;
                }else if (html == nextTxt) {                   
                    newPage = currentPage + 1;               
                }                                             
            }           
           
            //console.log(newPage);
           
            // set value of page in a limit form and submit it.           
            $('#page').val(newPage);
            $('#limit-form').submit();         

        });
    });
    
   
   
</script>
