<?php


    $sideBarContent = '
            Drag the marker if its at incorect place. 
            <p></p>
           ';
  //  $this->sideBarElement('Marker', $sideBarContent, array('class' => 'side-bar-info','break'=>true));


?>

<?php
    // load google maps api
    $this->headScript()->appendFile('http://maps.google.com/maps/api/js?sensor=false&region=PL', $type = 'text/javascript');
?>  

<?php
if ($this->showSteps) {
    echo $this->partial('_partials/acc-add-steps-desc.phtml', null, array('active' => 'step2'));
}
?>



<div class="grid_6">  
    <h2><?php echo $this->title;?></h2>
</div>

 <div id="map" class="grid_6 " style="height: 600px">  </div>

    
 <script type="text/javascript" src="<?php echo $this->baseUrl('/js/mapedit.js');?>"></script>
    

<div class="grid_6">
    <?php echo $this->form; ?>
</div>
