<?php
if (isset($this->acc) && count($this->acc->photosurls) > 0) {
    $imgsHtml = $this->partial('_partials/acc-photos.phtml',array('acc' => $this->acc));
    $this->sideBarElement('Current photos', $imgsHtml);
}
?> 


<?php
    echo $this->sideBarElement('Photos','partialfile:acc-add-step3',  array('class' => 'side-bar-info'));
?>

<h1><?php echo $this->translate('Change photos');?></h1>
<div class="grid_6 alpha">
    <?php echo $this->form;?>
</div>

