<?php
if ($this->preview == true) {
    //  echo $this->partial('_partials/acc-add-steps-desc.phtml', null, array('active' => 'step4'));
}
?>
<?php
if ($this->preview != true) {
    $sideBarHtml = '<ul>';

    if ($this->form) {
        $sideBarHtml .= '<li id="query-form"><div id="email-send-form">' . $this->form . '</div></li>';
    }
    $sideBarHtml .= '</ul>';
    $this->sideBarElement('Send query ', $sideBarHtml);
}
?>    

<?php
if ($this->acc->user->contactDetailsAvaliable() == true) {
    $sideBarHtml = '<ul>';
    
    if ($this->acc->user->phone_public == true && strlen($this->acc->user->phone) > 4) {
        $sideBarHtml .= '<li><strong>Phone:</strong> ' . $this->acc->user->phone . '</li>';
    }
    if ($this->acc->user->email_public == true) {
        $sideBarHtml .= '<li><strong>Email:</strong> ' . $this->mailHide($this->acc->user->email) . '</li>';
    }
    $sideBarHtml .= '</ul>';

    $this->sideBarElement('Contact details', $sideBarHtml);
}
?>
<?php
// <?php echo $this->gravatar($this->user['email'], array('imgSize' => 100, 'defaultImg' => 'identicon')); 
if (strlen($this->acc->user->description) > 0) {
    //$sideBarHtml = '<ul class="photos">';
    //$sideBarHtml .= '<li>'.$this->gravatar($this->user['email'], array('imgSize' => 100, 'defaultImg' => 'identicon')) .'</li>';
    //$sideBarHtml .= '</ul>';
    $sideBarHtml = '<ul>';
    $sideBarHtml .= '<li>' . $this->acc->user->description . '</li>';
    $sideBarHtml .= '</ul>';

    $this->sideBarElement('About ' . $this->acc->user->nickname, $sideBarHtml);
}
?>




<?php
if (count($this->acc->photosurls) > 0) {
    echo '<script type="text/javascript">  Shadowbox.init();</script>';

    $thumbs = $this->acc->thumbsurls;

    $imgsHtml = '';
    $imgsHtml .= '<ul class="photos">';
    foreach ($this->acc->photosurls as $photo_id => $url) {
        $thumb = '<img src="' . $thumbs[$photo_id] . '" alt="thumbs" width="160px" heigth="118px" />';
        $imgsHtml .= '<li>';
        $imgsHtml .= '<a href="' . $url . '" rel="shadowbox[accommodation]"/>' . $thumb . '</a>';
        $imgsHtml .= '</li>';
    }
    $imgsHtml .= '</ul>';
    //  echo '<script type="text/javascript">  $("#pikame").PikaChoose(); </script>';

    $this->sideBarElement('Photos', $imgsHtml);
} else {
    $this->sideBarElement('Photos', '<ul><li>No photos avaliable</li></ul>');
}
?>   


<?php
if ($this->preview == true) {
    $sideBarContent = "
            Your advertisment has just been added to our system. 
            However it has <strong>not been yet activated</strong>.";

    if ($this->isLogged()) {
        $sideBarContent .= " <p> If you happy with it then <br /><br />
   <a class=\"acc-add\" href=\"{$this->baseUrl('/accommodation/enable/id/' . $this->acc->acc_id)}\" alt=\"Activate\">Activate it now</a>
  <br /><br />  If you want to <strong>change</strong> something go <a href=\"{$this->baseUrl('/user/')}\">here</a>.
 </p>";
    } else {
        $sideBarContent .= "<p>To activate it or make changes, please <a href=\"{$this->baseUrl('/login/')}\">login</a>. </p> ";
    }

    $this->sideBarElement('Success!', $sideBarContent, array('class' => 'side-bar-info', 'break' => true));
}
?>

<?php if ($this->preview == true): ?>
    <div class="grid_6">  
        <h2>Step 4/4: Preview</h2>
    </div>
<?php endif; ?>

<?php //if (!($this->viewCache()->start('acc' . (string) $this->acc->acc_id))): ?>

    <div class="grid_6 ">&nbsp;</div>
    <h1 class="title"><?php echo $this->acc->title; ?></h1>
    <div id="acc-details" class="grid_6 alpha">    

        <div class="section grid_4 alpha">
            <h1 class="title">Description</h1>
            <p>
                <?php echo $this->acc->description; ?>
            </p>
        </div>
        <div class="section grid_2 omega" >
            <dl class="basic-info">
                <dt>Price (per month)</dt>
                <dd><?php echo $this->acc->price; ?> PLN</dd>
                <dt>Bond</dt>
                <dd><?php echo $this->acc->bond; ?> PLN</dd>

                <?php if (strlen($this->acc->price_info) > 0): ?>            
                    <dt>Additional expenses</dt>
                    <dd><?php echo $this->acc->price_info; ?></dd>        
                <?php endif; ?>

                <dt>Avaliable <?php echo $this->avaliable($this->acc)->inOrFrom(); ?>:</dt>
                <dd><?php echo $this->avaliable($this->acc)->time(); ?></dd>
                <dt>Address</dt>
                <dd><?php echo $this->address($this->acc); ?></dd>        
            </dl>

        </div>

        <div class="section grid_6 alpha">
            <h1>Map view</h1> 

        </div>

        <?php
        $lat = $this->acc->address->lat;
        $lng = $this->acc->address->lng;

        if (!empty($lat) && !empty($lng)) {
            echo '<input type="hidden" id="addr_lat" value="' . $lat . '" />';
            echo '<input type="hidden" id="addr_lng" value="' . $lng . '" />';
            echo '<input type="hidden" id="label" value="' . $this->address($this->acc) . '" />';
            echo '<div id="map" class="grid_6 alpha" style="height: 300px"> </div>';
            // load google maps api
            $this->headScript()->appendFile(
                    'http://maps.google.com/maps/api/js?sensor=false&region=PL', $type = 'text/javascript'
            );
        }
        ?>
        <script type="text/javascript" src="<?php echo $this->baseUrl('/js/mapshow.js'); ?>"></script>



        <?php if ($this->acc instanceof My_Houseshare_Shared): ?>
            <div class="section grid_2 alpha">
                <h1>Current tenants</h1> 
                <dl class="details">
                    <dt>Number of roomates</dt>
                    <dd><?php echo $this->acc->roomates->no_roomates; ?> </dd>
                    <dt>Approx. min age</dt>
                    <dd><?php echo $this->acc->roomates->min_age; ?> </dd>
                    <dt>Approx. max age</dt>
                    <dd><?php echo $this->acc->roomates->max_age; ?> </dd>
                    <dt>Gender</dt>
                    <dd><?php echo $this->acc->roomates->gender; ?> </dd>
                   <?php  if ($this->acc->roomates->description) {
                       echo '<dt>Other</dt>';
                       echo '<dd>' . $this->acc->roomates->description . '</dd>';
                    }
                ?>

                </dl>
            </div>
        <?php elseif ($this->acc instanceof My_Houseshare_Appartment): ?>
            <div class="section grid_2 alpha">
                <h1>Appartment details</h1>             
                <dl class="details">
                    <dt>Number of bedrooms</dt>
                    <dd><?php echo $this->acc->details->bedrooms; ?> </dd>
                    <dt>Number of bathrooms</dt>
                    <dd><?php echo $this->acc->details->bathrooms; ?> </dd>
                    <dt>Number of parking spots</dt>
                    <dd><?php echo $this->acc->details->parking_spots; ?> </dd>
                    <dt>Furniture</dt>
                    <dd><?php echo $this->acc->details->furnished; ?> </dd>
                    <dt>Other</dt>
                    <dd><?php echo $this->acc->details->description; ?> </dd>
                </dl>
            </div>    
        <?php endif; ?>

        <div class="section grid_2 alpha  ">
            <h1>Preferences</h1> 
            <?php
            $prefs = $this->acc->preferences;
            if (count($prefs) > 0) {
                echo '<ul class="feats-prefs">';
                foreach ($prefs as $p) {
                    echo '<li>' . $p->getName() . '</li>';
                }
                if ($this->acc->preferences_info) {
                    echo '<li class = "other"> Other: ' . $this->acc->preferences_info . '</li>';
                }
                echo '</ul>';
            }
            ?>
        </div>

        <div class="section grid_2 omega ">
            <h1>Features</h1> 
            <?php
            $features = $this->acc->features;
            if (count($features) > 0) {
                echo '<ul class="feats-prefs">';
                foreach ($features as $f) {
                    echo '<li>' . $f->getName() . '</li>';
                }                
                if ($this->acc->features_info) {
                    echo '<li class = "other"> Other: ' . $this->acc->features_info . '</li>';
                }
                echo '</ul>';
            }
            ?>
        </div>



    </div>

<?php
//$this->viewCache()->end();
//endif;
?>



<script type="text/javascript">
    $(function() {
        
        /*
         * Script for submit send query form using ajax.
         */
        
        var baseUrl = '<?php echo $this->baseUrl('/'); ?>';
        
        $("input#send").click(function() {
            // validate and process form here
            
            $('#form-sendemail').validate({
                rules: {
                    email: {
                        required: true,
                        email: true
                    },
                    message: "required"
                },
                messages: {
                    email: 'Please enter a valid email address',
                    message:  'You query cannot be empty'
                },
                submitHandler: function() {
                    var accID = $("input#acc_id").val();
                    var email = $("input#email").val();
                    var message = $("textarea#message").val();
        
                    var dataString = 'acc_id=' + accID + '&email=' + email + '&message=' + message;                    
                    
                    
                    $('#query-form').html('<div style="width:100%"> <img class="loadingimg" src="'+baseUrl+'images/loading2.gif" /></div>');
                    
        
                    $.ajax({
                        type: "POST",
                        url: baseUrl + "accommodation/query",
                        data: dataString,
                        success: function(data) {
                            $('#query-form').html(data)              
                            .hide()
                            .fadeIn(1500);
                        }
                    });
                    return false;
                }
            });
            
        });              
        
    });
  
</script>
