

<div>


    <?php
    if (count($this->acc->photosurls) > 0) {
         echo '<script type="text/javascript">  Shadowbox.init();</script>';
         
        $thumbs = $this->acc->thumbsurls; 
         
        $imgsHtml = '';
        $imgsHtml .= '<ul class="photos">';
        foreach ($this->acc->photosurls as $photo_id => $url) {                     
               $thumb = '<img src="'.$thumbs[$photo_id].'" alt="thumbs" width="160px" heigth="118px" />';
               $imgsHtml .= '<li>';
               $imgsHtml .= '<a href="' . $url . '" rel="shadowbox[accommodation]"/>'.$thumb.'</a>';
               $imgsHtml .= '</li>';
        }
        $imgsHtml .= '</ul>';
      //  echo '<script type="text/javascript">  $("#pikame").PikaChoose(); </script>';
       $this->layout()->customBox = $imgsHtml;       
    }  
    ?>   


</div>
<div id="acc-details">
    <h1 class="title"><?php echo $this->acc->title; ?></h1>
    <p>
        <?php echo $this->acc->description; ?>
    </p>
    <dl class="basic-info">
        <dt>Price:</dt>
        <dd><?php echo $this->acc->price; ?> (per month)</dd>
        <dt>Bond:</dt>
        <dd><?php echo $this->acc->bond; ?></dd>
        <dt>Avaliable from:</dt>
        <dd><?php echo $this->acc->date_avaliable; ?></dd>
    </dl>



    <div class="section">
        <h1>Where</h1> 
        <?php
        var_dump($this->acc->address->toArray());
        ?>
    </div>
    <div class="section">
        <h1>Features</h1> 
        <?php
        $features = $this->acc->features;
        if (count($features) > 0) {
            echo '<ul class="feats-prefs">';
            foreach ($features as $f) {
                echo '<li>' . $f->getName() . '</li>';
            }
            echo '</ul>';
        }
        ?>
    </div>

    <div class="section">
        <h1>Preferences</h1> 
        <?php
        $prefs = $this->acc->preferences;
        if (count($prefs) > 0) {
            echo '<ul class="feats-prefs">';
            foreach ($prefs as $p) {
                echo '<li>' . $p->getName() . '</li>';
            }
            echo '</ul>';
        }
        ?>
    </div>

    <div class="section">
        <h1>Roomates</h1> 
<?php
var_dump($this->acc->roomates->toArray());
?>
    </div>


    <div class="section">
        <h1>Contact</h1> 
        <a href="javascript:none;" id="ask-question">Ask a question</a>
        <div id="email-send-form">
            <?php echo $this->form; ?>        
        </div>
    </div>

</div>


<script type="text/javascript">      
    
    errors = <?php echo $this->errors; ?>;
     
    if (1 === errors) {
        $(window).scrollTop($('#send').position().top);
    }
    
    $(function() { 
        
        $('#ask-question').click(function() {
            $('#email-form').toggle('slow');
        });        
        
    });
    
</script>