<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />       

        <?php
        $cache = Zend_Registry::get('genericCache');

        $headers = $cache->load('headers');

        if (!$headers) {

            // CSS  ; 
            // $this->headLink()->appendStylesheet('http://960ls.atomidata.com//static/cssserve/2011/3/20/a9ee67bb90b44f8eb9ebe4e630122280.css');
            $this->headLink()->appendStylesheet($this->baseUrl('/css/grid960.css'));
            $this->headLink()->appendStylesheet($this->baseUrl('/css/layout.css'));
            $this->headLink()->appendStylesheet($this->baseUrl('/css/ui-lightness/jquery-ui-1.8.12.custom.css'));
            $this->headLink()->appendStylesheet($this->baseUrl('/css/shadowbox.css'));
            $this->headLink()->appendStylesheet($this->baseUrl('/css/jqtransform.css'));
            //  $this->headLink()->appendStylesheet($this->baseUrl('/css/right-without.css'));
            // jQuery  
            $this->headScript()->prependFile($this->baseUrl('/js/jquery-ui-1.8.7.custom.min.js'));
            $this->headScript()->prependFile($this->baseUrl('/js/jquery.ui.datepicker-pl.js'));
            $this->headScript()->prependFile($this->baseUrl('/js/jquery-1.6.1.min.js'));

            //   $this->headScript()->appendFile($this->baseUrl('/js/jquery.formtips.1.2.3.packed.js'));
            // $this->headScript()->appendFile($this->baseUrl('/js/jquery.corner.js'));
            $this->headScript()->appendFile($this->baseUrl('/js/jquery.qtip-1.0.0-rc3.min.js'));
            $this->headScript()->appendFile($this->baseUrl('/js/shadowbox.js'));
            $this->headScript()->appendFile($this->baseUrl('/js/jquery.validate.js'));
            $this->headScript()->appendFile('http://maps.google.com/maps/api/js?sensor=false&region=PL');

            $this->headScript()->appendFile($this->baseUrl('/js/markerwithlabel.js'));
            $this->headScript()->appendFile($this->baseUrl('/js/advertpreviewdialog.js'));
            $this->headScript()->appendFile($this->baseUrl('/js/jquery.jqtransform.js'));            
            $this->headScript()->appendFile($this->baseUrl('/js/jquery.limit-1.2.source.js'));



            // the application specific 
            $this->headScript()->appendFile($this->baseUrl('/js/houseshare_acc.js'));
            
            // openid-selector            
            $this->headLink()->appendStylesheet($this->baseUrl('/css/openid.css'));
            $this->headScript()->appendFile($this->baseUrl('/js/openid-jquery.js'));
            $this->headScript()->appendFile($this->baseUrl('/js/openid-en.js'));
           
           // $this->headScript()->appendFile($this->baseUrl('/js/myjs-min.js'));            


            $headers = (string) $this->headTitle($this->translate('ShareHouse: database of rooms and appartments for rent'));
            $headers .= (string) $this->headMeta()->appendName('keywords', $this->keywords);
            $headers .= (string) $this->headLink();
            $headers .= (string) $this->headScript();

            $cache->save($headers, 'headers');
        }

        echo $headers;
        ?>

        <!--[if IE 6]>
             <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('/css/grid960_myie6.css'); ?>" />
        <![endif]-->


        <link rel="shortcut icon" 
              href="<?php echo $this->baseUrl('/images/flavicon.gif'); ?>" 
              type="image/x-icon" 
              />


        <script type="text/javascript">

            // set some JS global values to be used in the app.            
            var myGlobals = {};
            
            // set baseUrl
            myGlobals.baseUrl = '<?php echo $this->baseUrl();?>';
            
            // set language, i.e. locale
            myGlobals.lang = '<?php echo Zend_Registry::get('Zend_Locale')->getLanguage(); ?>';                       
            if ('en' == myGlobals.lang) {
                myGlobals.lang = '';
            }
            
            //some translations for JS:
            myGlobals.charPrefix = '<?php echo $this->translate('You have'); ?>';
            myGlobals.charSuffix = '<?php echo $this->translate('characters left.'); ?>';
            
            //center of Poland
            myGlobals.lat = 52.385459
            myGlobals.lng = 19.131691
            
        </script>

    </head>


    <body>

        <div id="wrap">
            <div id="top-margin-color"></div>
            <div id="header" class="container_8">

                <div id="" class="grid_3 ">
                    <div>
                        <a href="<?php echo $this->baseUrl(); ?>"> 
                            <img src="<?php echo $this->baseUrl('/images/house_with_bg_beta.png'); ?>" 
                                 alt="ShareHouse.com" style="float:left"/> 
                        </a>
                    </div>
                    <div>
                        <h1><a href="<?php echo $this->baseUrl(); ?>">
                                <?php echo $this->translate('ShareHouse'); ?>
                            </a>
                        </h1> 


                        <h2><?php echo $this->translate('Its not complicated'); ?></h2> 
                    </div>

                </div>

                <div id="" class="grid_5 ">
                    <div id="login"><?php echo $this->profileLink(); ?> </div>
                </div>

                <?php //echo $this->navigation()->menu(); ?>

            </div>

            <div id="content" class="container_8">

                <div id="" class="grid_6">
                    <?php if ($this->getHelper('flashMessenger')->hasMassages()): ?>

                        <div  class="flashmessage" >                           
                            <p style="font-size: 14px;"> <?php echo $this->flashMessenger(); ?></p>   
                        </div>                        
                    <?php endif; ?>

                    <div  class="browser-version-varing" style="display:none">    
                        <?php
                        echo $this->translate(
                                'The website may not work well with Internet Explorer 6 or less'
                        );
                        ?>
                    </div>

                    <script type="text/javascript">
                        (function() {
                            if($.browser.msie && $.browser.version.substr(0,1)<7) {
                                $('.browser-version-varing').show();                                
                            }
                        })();
                    </script>


                    <!-- show breadcrumbs if avaliable -->
                    <?php $breadcrumbs = $this->navigation()->breadcrumbs(); ?>
                    <?php if (strlen($breadcrumbs) > 1): ?>
                        <div id="breadcrumbs">
                            <?php echo $breadcrumbs; ?>
                        </div>                    
                    <?php endif; ?>


                    <!-- show main content of the page -->
                    <div>    
                        <?php echo $this->layout()->content; ?>    
                    </div>
                </div>            


                <div id="" class="grid_2">






                    <?php
// display all side-bar boxes
                    echo $this->placeholder('side-bar');
                    ?>






                </div>

            </div>



            <div style="height:15px;"></div>

        </div>
        <div id="footer">
            <div class="footerWrapper">

                <p>
                    <a href="<?php echo $this->url(array(), 'aboutpage'); ?>" ><?php echo $this->translate('about'); ?></a>
                    |                   
                    <a href="<?php echo $this->url(array(), 'legalpage'); ?>" ><?php echo $this->translate('legal'); ?></a>
                    |
                    <a href="<?php echo $this->url(array(), 'privacypage'); ?>" ><?php echo $this->translate('privacy policy'); ?></a>
                    |
                    <a href="<?php echo $this->url(array(), 'contactpage'); ?>" ><?php echo $this->translate('contact'); ?></a>                     
                    | 
                    <a href="javascript:UserVoice.showPopupWidget();" 
                       title="Open feedback & support dialog (powered by UserVoice)">
                           <?php echo $this->translate('feedback always welcome'); ?>
                    </a>
                </p>     
            </div>

        </div>
        <script type="text/javascript">
            var uvOptions = {};
            (function() {
                var uv = document.createElement('script'); uv.type = 'text/javascript'; uv.async = true;
                uv.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'widget.uservoice.com/LoXsEoLVDTwwze3tLreIGg.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(uv, s);
            })();
        </script>
    </body>
</html>       






