<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />       

        <?php
        echo $this->headTitle('ShareHouse: Its not complicated');
        echo $this->headMeta()->appendName('keywords', $this->keywords);
        ?>

        <?php
        // CSS  ; 
        // $this->headLink()->appendStylesheet('http://960ls.atomidata.com//static/cssserve/2011/3/20/a9ee67bb90b44f8eb9ebe4e630122280.css');
        $this->headLink()->appendStylesheet($this->baseUrl('/css/grid960.css'));
        $this->headLink()->appendStylesheet($this->baseUrl('/css/layout.css'));
        $this->headLink()->appendStylesheet($this->baseUrl('/css/ui-lightness/jquery-ui-1.8.12.custom.css'));
        $this->headLink()->appendStylesheet($this->baseUrl('/css/shadowbox.css'));
        //$this->headLink()->appendStylesheet($this->baseUrl('/css/jqtransform.css'));
        //  $this->headLink()->appendStylesheet($this->baseUrl('/css/right-without.css'));
        ?>



        <?php
        // jQuery  
        $this->headScript()->prependFile($this->baseUrl('/js/jquery-ui-1.8.7.custom.min.js'));
        $this->headScript()->prependFile($this->baseUrl('/js/jquery-1.4.4.min.js'));
        
        //   $this->headScript()->appendFile($this->baseUrl('/js/jquery.formtips.1.2.3.packed.js'));
        $this->headScript()->appendFile($this->baseUrl('/js/jquery.corner.js'));
        $this->headScript()->appendFile($this->baseUrl('/js/jquery.qtip-1.0.0-rc3.min.js'));
        $this->headScript()->appendFile($this->baseUrl('/js/shadowbox.js'));
        $this->headScript()->appendFile('http://maps.google.com/maps/api/js?sensor=false&region=PL');
        ?>        


        <?php // the application specific  ?>
        <?php $this->headScript()->appendFile($this->baseUrl('/js/houseshare.js')); ?>
        <?php
        if ($this->controller() == 'accommodation') {
            $this->headScript()->appendFile($this->baseUrl('/js/houseshare_acc.js'));
        }
        ?>

        <?php // openid-selector  ?>
        <?php
        if ($this->controller() == 'user' || $this->controller() == 'accommodation') {
            $this->headLink()->appendStylesheet($this->baseUrl('/css/openid.css'));
            $this->headScript()->appendFile($this->baseUrl('/js/openid-jquery.js'));
            $this->headScript()->appendFile($this->baseUrl('/js/openid-en.js'));
        }
        ?>

        <?php //render the headLink and headScript  ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headScript(); ?>

    </head>


    <body>



        <div id="header" class="container_8">

            <div id="" class="grid_3 ">
                <div>
                    <a href="<?php echo $this->baseUrl(); ?>"> 
                        <img src="<?php echo $this->baseUrl('/images/house.png'); ?>" 
                             alt="ShareHouse.com" style="float:left"/> 
                    </a>
                </div>
                <div>
                    <h1><a href="<?php echo $this->baseUrl(); ?>">
                            <?php echo $this->translate('ShareHouse'); ?>
                        </a></h1> 


                    <h2><?php echo $this->translate('Its not complicated'); ?></h2> 
                </div>

            </div>

            <div id="" class="grid_5 ">
                <div id="login"><?php echo $this->profileLink(); ?> </div>
            </div>

        </div>



        <div id="content" class="container_8">

            <div id="" class="grid_6">
                <?php if ($this->getHelper('flashMessenger')->hasMassages()): ?>
                    <div id="dialog-message" title="Message">
                        <p style="font-size: 14px;"> <?php echo $this->flashMessenger(); ?></p>   
                    </div>

                    <script>
                        $( "#dialog-message" ).dialog({
                            modal: true,
                            draggable: false,
                            buttons: {
                                Ok: function() {
                                    $( this ).dialog( "close" );
                                }
                            }
                        });
                    </script>

                <?php endif; ?>    

                <?php echo $this->layout()->content; ?>    
            </div>            


            <div id="" class="grid_2">






                <?php
                // display all side-bar boxes
                echo $this->placeholder('side-bar');
                ?>






            </div>

        </div>

        <div style="clear:both"></div>



        <div class="footerWrapper">


            <p>
                about | info | faq | contact us
            </p>     
        </div>




    </body>
</html>       






