
<table id="resent-adverts">   
    <thead>
        <tr><th><?php echo $this->translate($this->title); ?></th></tr>
    <tbody>

        <?php foreach ($this->accommodations as $acc): ?>
         <!-- <tr>
                <td><?php //echo $this->timeSince(strtotime($acc->created),1); ?></td>
            </tr>-->
            <tr>
                <td><?php echo $this->partial('_partials/listing-preview.phtml', null, array('acc' => $acc)); ?></td>
            </tr>


            <?php if (isset($this->editMenu) && true === $this->editMenu): ?>
                <tr>
                    <td class="acc-edit-menu">

                        <a href="<?php echo $this->baseUrl('/accommodation/edit/id/' . $acc->acc_id); ?>">Edit</a> 
                        |
                        <a href="<?php echo $this->baseUrl('/accommodation/photochange/id/' . $acc->acc_id); ?>">Change photos</a>
                        |            
                        <a href="<?php echo $this->baseUrl('/accommodation/map/id/' . $acc->acc_id); ?>">Change localization on map</a>
                        |
                        <?php if ($acc->is_enabled == 1): ?>
                            <a href="<?php echo $this->baseUrl('/accommodation/disable/id/' . $acc->acc_id); ?>">Deactivate</a>               
                        <?php else: ?>             
                            <a href="<?php echo $this->baseUrl('/accommodation/enable/id/' . $acc->acc_id); ?>"><span style="color: green;"><strong>Activate</strong></span></a>               
                        <?php endif; ?>   

                    </td>
                </tr>
            <?php endif; ?>

        <?php endforeach; ?>
    </tbody>

</table>
<div>

    <div  id="progress"  style="display:none; width:100%"> 
       <img class="loadingimg"  src="/sharehouse/public/images/loading2.gif" />
    </div>
    
<?php //if ($this->isAjax !== true): ?>    

        <?php
        if ($this->accommodations instanceof Zend_Paginator) {
            echo $this->paginationControl(
                    $this->accommodations, 
                    'Sliding',
                    '_partials/pagination_control.phtml'                    
                   );
        }
        ?>    
    </div>

    <script type="text/javascript">
        $(document).ready(function () {
            $('.paginationControl').find('a').live('click', function(e) {
                var link = $(this);
                var href = link.attr('href');
                href = "/sharehouse/public/index/get-recent-adverts/page/2"
                // alert('asdf');      
                $('#resent-adverts').empty();
                $('#progress').show();
                $( 'html, body' ).animate( { scrollTop: 0 }, 'slow' );
                $('#progress').html('<img class="loadingimg" src="/sharehouse/public/images/loading2.gif" />');
                //$('#resent-adverts').empty().html('<div style="width:100%"> <img class="loadingimg" src="http://localhost.com/sharehouse/public/images/loading2.gif" /></div>');                                       
             //   $('#resent-adverts').load(href);
               // return false;
            });
        });    

    </script>

<?php //endif;?>
