
<table id="resent-adverts">   
    <thead>
        <tr><th>Recent advertisements</th></tr>
    <tbody>
        <?php foreach ($this->accommodations as $acc): ?>
        <tr>
            <td><?php echo $this->partial('_partials/listing-preview.phtml',null, array('acc'=> $acc));?></td>
            
        </tr>
        <?php endforeach;?>
    </tbody>
        
</table>

<?php //var_dump($this->accommodations);?>