
<?php

$steps = array();

// step 1
$steps['step1'] = array(
        'title' => 'Step 1: Basic information',
        'content'=> 'In this step basic information about your accommodation is provided.   
            <p></p>

       ');


// step 2
$steps['step2'] = array(
        'title' => 'Step 2: Map localization',
        'content'=> 'Based on the address provided at step 1, localization on the map will be 
            specified autmatically. 
            <p>
            However, at this step you will be able to verify the localization and, if needed,
            to correct it.
            </p>
       
       ');


// step 3
$steps['step3'] = array(
        'title' => 'Step 3: Photos',
        'content'=> 'Up to <strong>five</strong> photos can be accompany your addvertisment.               
            <p></p>
       ');



foreach ($steps as $key=>$value) {
    $class = ' inactive-step';
    if ($this->active == $key) {
        $class = ' current-step';
    }
    $this->sideBarElement($value['title'], $value['content'], array('place' => 'append', 'class' => 'side-bar-info ' . $class,'break'=>true));
}

?>