<table class="details">
    <tbody>
        <?php
        $data = $this->data;
        $labels = $this->data->getLabels();

        foreach ($data as $name => $value) {

            if (strpos($name, '_id') > 3 || is_null($value)
                    || strlen($value) == 0 || $name == 'description') {
                continue;
            }


            $nameLabel = $name;
            $valueLabel = $value;

            if (array_key_exists($name, $labels)) {
                $nameLabel = $labels[$name]['label'];
                // check if a label for a value exists

                if (array_key_exists('value', $labels[$name]) && isset($labels[$name]['value'][$value])) {
                    $valueLabel = $labels[$name]['value'][$value];
                }
            }
            
          //  $img = "<img style=\"vertical-align:middle;\" src=\"{$this->baseUrl('/icons/bedrooms.gif')}\" alt=\'$nameLabel\'/>";

            echo "<tr>";
           // echo "<td class=\"name\">$img</td>";
            echo "<td class=\"name\">{$this->translate($nameLabel)}</td>";
            echo "<td class=\"value\">{$this->translate($valueLabel)}</td>";
            echo "</tr>";
        }

        $description = $data['description'];
        if (strlen($description) > 0) {                                 
            echo "<tr><td class=\"other\" colspan=\"2\">{$this->translate('Other')}: $description</td></tr>";            
        }
        ?>
    </tbody>
</table>
