
<?php

$steps = array();

// step 1
$steps['step1'] = array(
        'title' => 'Step 1: Basic information',
        'content'=> 'partialfile:acc-add-step1'
);


// step 2
$steps['step2'] = array(
        'title' => 'Step 2: Map localization',
        'content'=> 'partialfile:acc-add-step2'
);


// step 3
$steps['step3'] = array(
        'title' => 'Step 3: Photos',
        'content'=> 'partialfile:acc-add-step3'
);

// step 4
$steps['step4'] = array(
        'title' => 'Step 4: Preview',
        'content'=> 'partialfile:acc-add-step4'
);

foreach ($steps as $key=>$value) {
    $class = ' inactive-step';
    if ($this->active == $key) {
        $class = ' current-step';
    }
    $this->sideBarElement($value['title'], $value['content'], array('place' => 'append', 'class' => 'side-bar-info ' . $class,'break'=>true));
}

?>