<div class="side-bar-box">
<?php 
    if (true === $this->title) {
        echo '<h3>' . $this->translate('Spread the word') . '</h3>'; 
    }
?>
    <?php 
    // old add this
    $addThis = <<<END
 <ul>
        <li>
            <div class="addthis_toolbox addthis_default_style ">
               <!-- <a class="addthis_button_preferred_1"></a>-->                
                <a class="addthis_button_facebook"></a>
                <a class="addthis_button_twitter"></a>
                <a class="addthis_button_email"></a>               
                <a class="addthis_button_favorites"></a>
                <a class="addthis_button_delicious"></a>                
                <a class="addthis_button_compact"></a>
                <a class="addthis_button_google_plusone"></a>
               <!-- <a class="addthis_counter addthis_bubble_style"></a> -->
            </div>
            <script type="text/javascript">var addthis_config = {"data_track_clickback":true};</script>
            <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4dccd1b64ae64578"></script>
       
        </li>
   <ul>   
END;
    
    echo $addThis;
    ?>

</div>
