<div class="side-bar-box">
<?php 
    if (true === $this->title) {
        echo '<h3>' . $this->translate('Spread the word') . '</h3>'; 
    }
?>
    <ul>
        <li>
            <div class="addthis_toolbox addthis_default_style ">
               <!-- <a class="addthis_button_preferred_1"></a>-->
                <a class="addthis_button_facebook"></a>
                <a class="addthis_button_preferred_2"></a>
                <a class="addthis_button_preferred_3"></a>
                <a class="addthis_button_preferred_4"></a>
                <a class="addthis_button_preferred_5"></a>
                <a class="addthis_button_preferred_6"></a>
                <a class="addthis_button_preferred_7"></a>
                <a class="addthis_button_compact"></a>
                <a class="addthis_counter addthis_bubble_style"></a>
            </div>
            <script type="text/javascript">var addthis_config = {"data_track_clickback":true};</script>
            <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4dccd1b64ae64578"></script>
       
        </li>
   <ul>
</div>
