<dl class="listing-preview">
    <dt class="listing-preview-title">
        <a href="<?php echo $this->baseUrl('/show/' . $this->acc->acc_id);?>"><?php echo $this->acc->title;?></a>
    </dt>
    <dd>
        <dl>
            <dt>Rent:</dt><dd><?php echo $this->acc->price;?></dd>            
            <dt>City:</dt><dd><?php echo $this->acc->city;?></dd> 
            <dt>State:</dt><dd><?php echo $this->acc->state;?></dd> 
            <dt>User:</dt><dd><?php echo $this->acc->user->first_name;?></dd> 
        </dl>

    </dd>
</dl>