<div class="listing-preview">
    
    <?php
    $firstThumbPath = $this->baseUrl('/images/thumbs/no_pic.jpg');

    if (count($this->acc->photos) > 0) {
        $urls = $this->acc->thumbsurls;
        $firstThumbPath = array_shift($urls);
    }
    ?>
      <div class='listing-preview-img'>
    <a href="<?php echo $this->baseUrl('/accommodation/show/id/' . $this->acc->acc_id); ?>">
        <img src="<?php echo $firstThumbPath; ?>" alt="Thumb image" class="thumb" height="90px"  />
    </a>
        </div>
    <div class="listing-preview-detials" style="float:left">
        <h1 class="advert-title">
            <a href="<?php echo $this->baseUrl('/accommodation/show/id/' . $this->acc->acc_id); ?>">
            <?php echo  $this->truncate(ucfirst(strtolower($this->acc->title)),0, 60); ?>
            </a>
        </h1>
        <div class="advert-info" >

            <div> <?php echo $this->truncate($this->acc->description, 0, 120); ?></div>               
            <dl>
                <?php $city =  $this->acc->city . ', ' . $this->acc->state;?>
                <dt>City: </dt><dd><a href="<?php echo $this->baseUrl('/accommodation/list/city/' . $this->acc->address->city_id);?>"><?php echo $city;?></a></dd>                                                           
                <dt>Type: </dt><dd><?php echo $this->acc->type->name; ?></dd> 
                
                
                <dt>Avaliable <?php echo $this->avaliable($this->acc)->inOrFrom();?>: </dt>
                
                <dd>                 
                <?php echo $this->avaliable($this->acc)->time(); ?>
                </dd> 
            </dl>
            <dl class="advert-stats">
                <dt>Added: </dt><dd><?php echo $this->timeSince($this->acc->creationtimestamp) . ' ago by ' . $this->acc->user->name; ?></dd> 
                <dt>Views: </dt><dd><?php echo $this->acc->views_count; ?></dd> 
                <dt>Queries sent: </dt><dd><?php echo 5; ?></dd>                                                           
            </dl>
        </div>
    </div>
    <div class="listing-preview-price">
        <p class="value"><?php echo $this->acc->price; ?></p>
        <p><?php echo $this->translate('Per month');?></p>
    </div>
    <div style="float:clear"></div>
</div>
