<!--<div style="height:20px;">&nbsp;</div>-->
<div class="side-bar-box <?php echo $this->class; ?>">
    <?php
    if ($this->title) {
        echo '<h3>' . $this->translate($this->title) . '</h3>';
    }
    ?>
    <?php if (is_string($this->content)): ?>
        
        <?php echo $this->content; ?>
       
    <?php // else: ?>
        <?php //echo $this->content; ?>
    <?php endif; ?>

</div>
