<?php
$sideBarContent = 'partialfile:account-recovery';
$this->sideBarElement('Account Recovery', $sideBarContent, array('class' => 'side-bar-info'));  
?>

<h1><?php echo $this->translate('Account Recovery');?></h1>
<?php 
    if (count($this->form->getErrorMessages()) > 0 ) {
        $errors = $this->form->getErrorMessages();
        echo '<div class="form-invalid">';
        echo $this->translate($errors[0]);
        echo '</div>';
    }    
    echo $this->form;
?>