<?php
    $this->headScript()->prependFile($this->baseUrl('/js/houseshare_userreg.js'));
?>

<?php
 $sideBarContent = 'partialfile:create-account';
 $this->sideBarElement('What is this?',$sideBarContent, array('class' => 'side-bar-info'));  
?>
<div class="grid_6 alpha">    
    <h1><?php echo $this->translate('Create an account');?></h1>
    <?php echo $this->form ;?>
</div>

<script type="text/javascript">
    jQuery(function($){//jQuery ready        
       myCharsLeft('about_you-description', 100);        
    });
</script>