<?php
$str = "A user with the email %email% already exists in our database.";
$str = str_replace('%email%', $this->user->email, $this->translate($str));

echo "<h2>$str</h2>";
?>

<div class="grid_6">&nbsp</div>
<div class="grid_6 alpha">         
<?php

$loginUrl  = "<span class=\"side-bar-link\"><a href=\"{$this->baseUrl('/login')}\">".$this->translate('login _verb')."</a></span>";

if ($this->authProvider):

    $account = $this->authProvider->provider_type;
    $str = $this->translate("This user used %accont% to register. If you are this user please try to %login% using your %accont%.");
    $str = str_replace(array("%accont%", "%login%"), array("<strong>$account</strong>", $loginUrl), $str);
  
 else:

     $str = $this->translate("This user registered directly in our system.  If you are this user please try to %login% using your email and password.");
     $str = str_replace(array("%login%"), array($loginUrl), $str);
     
endif; 

echo $str;

?>

</div>
