<div>
    User account page.
    <?php echo $this->gravatar($this->user['email'], array('imgSize' => 100, 'defaultImg' => 'identicon')); ?>
    <?php var_dump($this->user); ?>
    <div>
        <a href="<?php echo $this->baseUrl('/user/edit'); ?>">Edit your data</a>
    </div>
    <?php if ($this->accs): ?>
        Your accommodations:        
        <?php foreach ($this->accs as $acc): ?>
            <?php var_dump($acc->toArray()); ?>
            <a href="<?php echo $this->baseUrl('/accommodation/edit/id/' . $acc->acc_id); ?>">Edit acc data</a> 
            |
             <a href="<?php echo $this->baseUrl('/accommodation/photochange/id/' . $acc->acc_id); ?>">Change acc photos</a>
            |            
            
            <?php if ($acc->is_enabled == 1): ?>
                 <a href="<?php echo $this->baseUrl('/accommodation/disable/id/' . $acc->acc_id); ?>">Disable</a>               
            <?php else: ?>             
                <a href="<?php echo $this->baseUrl('/accommodation/enable/id/' . $acc->acc_id); ?>">Enable</a>               
            <?php endif; ?>                             
                
        <?php endforeach;?>
        
        
    <?php endif; ?>

</div>

<div>
    <br />
    <a href="<?php echo $this->baseUrl('/add'); ?>">Add new accommodation</a>
</dvi>
