
<?php
$sideBarHtml = 'partialfile:top-cities';
$this->sideBarElement('Top cities', $sideBarHtml, array('place' => 'prepend'));
?>


<?php
  $sideBarContent = '<br/>
       <a class="acc-add" href="' . $this->baseUrl("/add").'" alt="Add accommodation">'.$this->translate('Add accommodation').'</a>
           <br/><br/>';
$this->sideBarElement('', $sideBarContent);
?>

<div class="grid_6">&nbsp;</div>
<div class="grid_3 alpha">  
    <h2><?php echo $this->translate('Your data');?></h2>
    <div class="grid_1 alpha">
        <?php echo $this->gravatar($this->user['email'], array('imgSize' => 100, 'defaultImg' => 'identicon')); ?>
    </div>
    <div class="grid_2 alpha">
        <table class="user-info">
            <tbody>
                <tr>
                    <td><?php echo $this->translate('Nickname');?>:</td>
                    <td><strong><?php echo $this->user['nickname']; ?></strong></td>
                </tr>
                <tr>
                    <td><?php echo $this->translate('Phone');?>:</td>
                    <td><?php echo $this->user['phone'];?></td>
                </tr>  
                <tr>
                    <td><?php echo $this->translate('Email');?>:</td>
                    <td><?php echo $this->user['email']; ?></td>
                </tr>  
                
            </tbody>
        </table>
        <div class="user-options">       
            <br/>
            <a href="<?php echo $this->baseUrl('/user/edit'); ?>"><?php echo $this->translate('Edit your data');?></a>
        </div>
    </div>
</div>
<div class="grid_3 omega">
    <h2><?php echo $this->translate('About you');?></h2>
    <p>
        <?php
        if (!empty($this->user['description'])) {
            echo $this->user['description'];
        } else {
            echo $this->translate('No infomration avaliable');
        }
        ?>
    </p>



</div>    
<div class="grid_6">&nbsp;</div>
<div class="grid_6 alpha">
    <?php if ($this->accs): ?>
        <h2><?php echo $this->translate('Your accommodations');?></h2>       


        <div>
            <?php
            echo $this->partial('_partials/_recentAdverts.phtml', null, array(
                'accommodations' => $this->accs,
                'title' => '',
                'editMenu' => true
                )
            );
            ?>
        </div>



    <?php endif; ?>

</div>


