<?php
$sideBarContent = <<<END
  You can create an ShareHase acconout using our 
  simple registration <a href="{$this->baseUrl('/user/create')}">form</a>      
      <p>Alternatively, account can be created for you when you add your first
      advertisment.
      </p>
END;

$this->sideBarElement('I don\'t want OpenID',$sideBarContent, array('class' => 'side-bar-info'));  
?>

<?php
$sideBarContent = <<<END
If you don't have an account, you can get free OpenID using
      <a href="https://www.myopenid.com/signup"> myOpenID </a>. 
<p>
  Alternatively, you can register into houseshare using our 
  simple registration <a href="{$this->baseUrl('/user/create')}">form</a>
</p>      
       
END;

$this->sideBarElement('I don\'t have OpenID',$sideBarContent, array('class' => 'side-bar-info',  'break'=>true));  
?>

<?php
   $sideBarContent = 'partialfile:why-openid';
   $this->sideBarElement('Why OpenID?',$sideBarContent, array('class' => 'side-bar-info', 'break'=>true));  
?>

<script type="text/javascript">

    var imgPath = '<?php echo $this->baseUrl('images/');?>';
   
    $(document).ready(function() {
        openid.img_path = imgPath;
        openid.init('openid_identifier');
        openid.setDemoMode(false); //Stops form submission for client javascript-only test purposes

    });
</script>

<div class="grid_6 ">&nbsp;</div>
<div class="grid_6 ">&nbsp;</div>
<div id="login-form" class="grid_3 alpha">
     <h2><?php echo $this->translate('Login using OpenID');?></h2>
    <!-- Simple OpenID Selector -->
    <form action="<?php echo $this->baseUrl('/user/login');?>" method="get" id="openid_form">
        <input type="hidden" name="action" value="verify" />
        <fieldset>
            <legend></legend>
            <div id="openid_choice">               
                <div id="openid_btns"></div>
            </div>
            <div id="openid_input_area">
                <input id="openid_identifier" name="openid_identifier" type="text" value="http://" />
                <input id="openid_submit" type="submit" value="Sign-In"/>
            </div>
            <noscript>
                <p>OpenID is service that allows you to log-on to many different websites using a single indentity.
				Find out <a href="http://openid.net/what/">more about OpenID</a> and <a href="http://openid.net/get/">how to get an OpenID enabled account</a>.
                </p>
            </noscript>
        </fieldset>
    </form>
    <!-- /Simple OpenID Selector -->
</div>

<div class="grid_3 omega">


    <h2><?php echo $this->translate('Login using our own system');?></h2>

    <div>
         <?php if (true == $this->failedLoginAttempt): ?>
         <div class="form-invalid">
            <?php echo $this->translate('Incorrect email or password');?>.
         </div>
         <?php endif;?>
        <?php echo $this->form; ?>
    </div>

</div>
<div class="grid_6 ">&nbsp;</div>
<div class="grid_6 " style="text-align: center">
    <h2><?php echo $this->translate('If you’ve forgotten or lost your login information');?></h2>
    <h2>
        <a class="acc-recovery" href="<?php echo $this->baseUrl('/user/account-recovery');?>">
            <?php echo $this->translate('click here to recover your login information');?>
        </a>
    </h2>
</div>

<script language="javascript">
    $(function(){
       // $('form').jqTransform({imgPath:'<?php// echo $this->baseUrl('/jqtimg/');?>'});
    });
</script>