<?php
   $sideBarContent = 'OpenID allows you to use an existing account to sign in to multiple websites, without needing to create new passwords.
                    <p style="text-align: right;">
                <a  href="http://openid.net/what/">Learn more</a>
                </p>
       
       ';
   $this->sideBarElement('Why OpenID?',$sideBarContent, array('class' => 'side-bar-info'));  
?>

<script type="text/javascript">

    var imgPath = '<?php echo $this->baseUrl('images/');?>';

    console.log(imgPath);

    $(document).ready(function() {
        openid.img_path = imgPath;
        openid.init('openid_identifier');
        openid.setDemoMode(false); //Stops form submission for client javascript-only test purposes

    });
</script>


<div id="login-form">
    <!-- Simple OpenID Selector -->
    <form action="<?php echo $this->baseUrl('/user/login');?>" method="get" id="openid_form">
        <input type="hidden" name="action" value="verify" />
        <fieldset>
            <legend></legend>
            <div id="openid_choice">
                <p>Do you already have an account on one of these sites? Click the logo to <strong>log in</strong> with it here:</p>
                <div id="openid_btns"></div>
            </div>
            <div id="openid_input_area">
                <input id="openid_identifier" name="openid_identifier" type="text" value="http://" />
                <input id="openid_submit" type="submit" value="Sign-In"/>
            </div>
            <noscript>
                <p>OpenID is service that allows you to log-on to many different websites using a single indentity.
				Find out <a href="http://openid.net/what/">more about OpenID</a> and <a href="http://openid.net/get/">how to get an OpenID enabled account</a>.</p>
            </noscript>
        </fieldset>
    </form>
    <!-- /Simple OpenID Selector -->
</div>
<h2>OR</h2>
<div>


    <p>Login using houseshare auth system. <br />If you don't have an account, please
        register to using free OpenID provider
        <a href="https://www.myopenid.com/signup"> myOpenID </a> or
        using houseshare registration <a href="
    <?php echo $this->baseUrl('/user/create');?> ">form</a>.
    </p>

    <div>
         <?php if (true == $this->failedLoginAttempt): ?>
        <h2>
            Incorrect email or password.
        </h2>
         <?php endif;?>
        <?php echo $this->form; ?>
    </div>

</div>
<!--
<div id="fb-root"></div>
      <script src="http://connect.facebook.net/en_US/all.js"></script>
      <script>
         FB.init({
            appId:'184175234953062', cookie:false,
            status:true, xfbml:true
         });
      </script>
      <fb:login-button> Facebook</fb:login-button>

-->